// Mocks generated by Mockito 5.4.6 from annotations
// in running_mate/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:running_mate/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i4;
import 'package:running_mate/features/auth/data/models/user_profile_model.dart'
    as _i3;
import 'package:running_mate/features/auth/domain/entities/auth_provider.dart'
    as _i7;
import 'package:running_mate/features/auth/domain/entities/auth_state.dart'
    as _i6;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileModel_1 extends _i1.SmartFake
    implements _i3.UserProfileModel {
  _FakeUserProfileModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i5.Stream<_i6.AuthState>.empty(),
          )
          as _i5.Stream<_i6.AuthState>);

  @override
  _i5.Future<_i2.User> signInWithProvider(_i7.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserProfileModel?> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i5.Future<_i3.UserProfileModel?>.value(),
          )
          as _i5.Future<_i3.UserProfileModel?>);

  @override
  _i5.Future<_i3.UserProfileModel> upsertProfile(
    _i3.UserProfileModel? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProfile, [profile]),
            returnValue: _i5.Future<_i3.UserProfileModel>.value(
              _FakeUserProfileModel_1(
                this,
                Invocation.method(#upsertProfile, [profile]),
              ),
            ),
          )
          as _i5.Future<_i3.UserProfileModel>);

  @override
  _i5.Future<bool> isNicknameAvailable(String? nickname) =>
      (super.noSuchMethod(
            Invocation.method(#isNicknameAvailable, [nickname]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> requestAccountDeletion(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#requestAccountDeletion, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAccountDeletion(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAccountDeletion, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
