import '../entities/achievement.dart';

final allAchievements = <Achievement>[
  // 거리
  const Achievement(
    id: 'first_step',
    name: '첫 발걸음',
    description: '첫 러닝을 완료했습니다',
    iconName: 'footprints',
    category: AchievementCategory.distance,
    conditionType: ConditionType.firstRun,
    conditionValue: 1,
    xpReward: 50,
  ),
  const Achievement(
    id: 'runner_5k',
    name: '5K 러너',
    description: '누적 5km를 달렸습니다',
    iconName: 'road',
    category: AchievementCategory.distance,
    conditionType: ConditionType.totalDistance,
    conditionValue: 5,
    xpReward: 50,
  ),
  const Achievement(
    id: 'half_marathon',
    name: '하프 마라토너',
    description: '누적 21km를 달렸습니다',
    iconName: 'medal',
    category: AchievementCategory.distance,
    conditionType: ConditionType.totalDistance,
    conditionValue: 21,
    xpReward: 100,
  ),
  const Achievement(
    id: 'full_marathon',
    name: '마라토너',
    description: '누적 42km를 달렸습니다',
    iconName: 'trophy',
    category: AchievementCategory.distance,
    conditionType: ConditionType.totalDistance,
    conditionValue: 42,
    xpReward: 150,
  ),
  const Achievement(
    id: 'century_club',
    name: '100km 클럽',
    description: '누적 100km를 달렸습니다',
    iconName: 'star',
    category: AchievementCategory.distance,
    conditionType: ConditionType.totalDistance,
    conditionValue: 100,
    xpReward: 300,
  ),
  // 연속
  const Achievement(
    id: 'streak_3',
    name: '3일 연속',
    description: '3일 연속으로 러닝했습니다',
    iconName: 'fire',
    category: AchievementCategory.streak,
    conditionType: ConditionType.streakDays,
    conditionValue: 3,
    xpReward: 50,
  ),
  const Achievement(
    id: 'weekly_warrior',
    name: '주간 전사',
    description: '7일 연속으로 러닝했습니다',
    iconName: 'flame',
    category: AchievementCategory.streak,
    conditionType: ConditionType.streakDays,
    conditionValue: 7,
    xpReward: 100,
  ),
  const Achievement(
    id: 'monthly_habit',
    name: '한 달 습관',
    description: '30일 연속으로 러닝했습니다',
    iconName: 'calendar_check',
    category: AchievementCategory.streak,
    conditionType: ConditionType.streakDays,
    conditionValue: 30,
    xpReward: 500,
  ),
  // 탐험
  const Achievement(
    id: 'explorer',
    name: '탐험가',
    description: '5개의 다른 코스를 완주했습니다',
    iconName: 'map',
    category: AchievementCategory.exploration,
    conditionType: ConditionType.courseCount,
    conditionValue: 5,
    xpReward: 50,
  ),
  const Achievement(
    id: 'course_master',
    name: '코스 마스터',
    description: '20개의 다른 코스를 완주했습니다',
    iconName: 'map_marked',
    category: AchievementCategory.exploration,
    conditionType: ConditionType.courseCount,
    conditionValue: 20,
    xpReward: 200,
  ),
  const Achievement(
    id: 'first_share',
    name: '첫 공유',
    description: '첫 코스를 공유했습니다',
    iconName: 'share',
    category: AchievementCategory.exploration,
    conditionType: ConditionType.courseShare,
    conditionValue: 1,
    xpReward: 50,
  ),
  // 속도
  const Achievement(
    id: 'pace_breaker_6',
    name: '6분 벽 돌파',
    description: '평균 페이스 6분/km 이하로 달렸습니다',
    iconName: 'speedometer',
    category: AchievementCategory.speed,
    conditionType: ConditionType.pace,
    conditionValue: 600, // 6분 = 600초/100으로 나눠서 6.0과 비교
    xpReward: 100,
  ),
  const Achievement(
    id: 'pace_breaker_5',
    name: '5분 벽 돌파',
    description: '평균 페이스 5분/km 이하로 달렸습니다',
    iconName: 'speedometer_fast',
    category: AchievementCategory.speed,
    conditionType: ConditionType.pace,
    conditionValue: 500,
    xpReward: 150,
  ),
  const Achievement(
    id: 'speed_demon',
    name: '스피드 데몬',
    description: '평균 페이스 4:30/km 이하로 달렸습니다',
    iconName: 'lightning',
    category: AchievementCategory.speed,
    conditionType: ConditionType.pace,
    conditionValue: 450,
    xpReward: 300,
  ),
  // 시간대
  const Achievement(
    id: 'early_bird',
    name: '얼리버드',
    description: '새벽 러닝 5회 완료',
    iconName: 'sunrise',
    category: AchievementCategory.time,
    conditionType: ConditionType.earlyRunCount,
    conditionValue: 5,
    xpReward: 100,
  ),
  const Achievement(
    id: 'night_owl',
    name: '나이트 올빼미',
    description: '야간 러닝 5회 완료',
    iconName: 'moon',
    category: AchievementCategory.time,
    conditionType: ConditionType.nightRunCount,
    conditionValue: 5,
    xpReward: 100,
  ),
  // 특별
  const Achievement(
    id: 'weekend_warrior',
    name: '주말 전사',
    description: '4주 연속 주말 러닝',
    iconName: 'weekend',
    category: AchievementCategory.special,
    conditionType: ConditionType.weekendStreak,
    conditionValue: 4,
    xpReward: 150,
  ),
  const Achievement(
    id: 'long_runner',
    name: '롱런 마스터',
    description: '한 번에 10km 이상 달리기',
    iconName: 'route',
    category: AchievementCategory.special,
    conditionType: ConditionType.singleDistance,
    conditionValue: 10,
    xpReward: 200,
  ),
];
