// Mocks generated by Mockito 5.4.6 from annotations
// in running_mate/test/features/course/data/repositories/course_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:running_mate/features/course/data/datasources/course_remote_datasource.dart'
    as _i3;
import 'package:running_mate/features/course/data/models/course_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCourseModel_0 extends _i1.SmartFake implements _i2.CourseModel {
  _FakeCourseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CourseRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRemoteDataSource extends _i1.Mock
    implements _i3.CourseRemoteDataSource {
  MockCourseRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.CourseModel>> getAllCourses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCourses, []),
            returnValue: _i4.Future<List<_i2.CourseModel>>.value(
              <_i2.CourseModel>[],
            ),
          )
          as _i4.Future<List<_i2.CourseModel>>);

  @override
  _i4.Future<_i2.CourseModel?> getCourseById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseById, [id]),
            returnValue: _i4.Future<_i2.CourseModel?>.value(),
          )
          as _i4.Future<_i2.CourseModel?>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<String>> getRecentCourseIds(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentCourseIds, [userId], {#limit: limit}),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> rateCourse({
    required String? courseId,
    required String? userId,
    required int? rating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rateCourse, [], {
              #courseId: courseId,
              #userId: userId,
              #rating: rating,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.CourseModel> createCourse(_i2.CourseModel? course) =>
      (super.noSuchMethod(
            Invocation.method(#createCourse, [course]),
            returnValue: _i4.Future<_i2.CourseModel>.value(
              _FakeCourseModel_0(
                this,
                Invocation.method(#createCourse, [course]),
              ),
            ),
          )
          as _i4.Future<_i2.CourseModel>);
}
