// Mocks generated by Mockito 5.4.6 from annotations
// in running_mate/test/features/auth/domain/usecases/check_auth_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:running_mate/features/auth/domain/entities/auth_provider.dart'
    as _i6;
import 'package:running_mate/features/auth/domain/entities/auth_state.dart'
    as _i5;
import 'package:running_mate/features/auth/domain/entities/user_profile.dart'
    as _i2;
import 'package:running_mate/features/auth/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i4.Stream<_i5.AuthState>.empty(),
          )
          as _i4.Stream<_i5.AuthState>);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  _i4.Future<_i2.UserProfile> signInWithProvider(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i4.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserProfile?> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i4.Future<_i2.UserProfile?>.value(),
          )
          as _i4.Future<_i2.UserProfile?>);

  @override
  _i4.Future<_i2.UserProfile> updateProfile(_i2.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i4.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#updateProfile, [profile]),
              ),
            ),
          )
          as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<bool> isNicknameAvailable(String? nickname) =>
      (super.noSuchMethod(
            Invocation.method(#isNicknameAvailable, [nickname]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> requestAccountDeletion() =>
      (super.noSuchMethod(
            Invocation.method(#requestAccountDeletion, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAccountDeletion() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAccountDeletion, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.AuthState> checkAuthState() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthState, []),
            returnValue: _i4.Future<_i5.AuthState>.value(_i5.AuthState.initial),
          )
          as _i4.Future<_i5.AuthState>);
}
