// Mocks generated by Mockito 5.4.6 from annotations
// in running_mate/test/features/course/domain/usecases/get_recommended_courses_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:running_mate/features/course/domain/entities/course.dart'
    as _i2;
import 'package:running_mate/features/course/domain/entities/running_context.dart'
    as _i10;
import 'package:running_mate/features/course/domain/entities/scored_course.dart'
    as _i9;
import 'package:running_mate/features/course/domain/entities/user_running_profile.dart'
    as _i7;
import 'package:running_mate/features/course/domain/repositories/course_repository.dart'
    as _i5;
import 'package:running_mate/features/course/domain/services/context_detector.dart'
    as _i3;
import 'package:running_mate/features/course/domain/services/course_scorer.dart'
    as _i4;
import 'package:running_mate/features/course/domain/services/recommendation_engine.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCourse_0 extends _i1.SmartFake implements _i2.Course {
  _FakeCourse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContextDetector_1 extends _i1.SmartFake
    implements _i3.ContextDetector {
  _FakeContextDetector_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourseScorer_2 extends _i1.SmartFake implements _i4.CourseScorer {
  _FakeCourseScorer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContextDetectionResult_3 extends _i1.SmartFake
    implements _i3.ContextDetectionResult {
  _FakeContextDetectionResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i5.CourseRepository {
  MockCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.Course>> getAllCourses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCourses, []),
            returnValue: _i6.Future<List<_i2.Course>>.value(<_i2.Course>[]),
          )
          as _i6.Future<List<_i2.Course>>);

  @override
  _i6.Future<_i2.Course?> getCourseById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseById, [id]),
            returnValue: _i6.Future<_i2.Course?>.value(),
          )
          as _i6.Future<_i2.Course?>);

  @override
  _i6.Future<_i7.UserRunningProfile?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i6.Future<_i7.UserRunningProfile?>.value(),
          )
          as _i6.Future<_i7.UserRunningProfile?>);

  @override
  _i6.Future<List<String>> getRecentCourseIds(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentCourseIds, [userId], {#limit: limit}),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> rateCourse({
    required String? courseId,
    required String? userId,
    required int? rating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rateCourse, [], {
              #courseId: courseId,
              #userId: userId,
              #rating: rating,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Course> shareCourse(_i2.Course? course) =>
      (super.noSuchMethod(
            Invocation.method(#shareCourse, [course]),
            returnValue: _i6.Future<_i2.Course>.value(
              _FakeCourse_0(this, Invocation.method(#shareCourse, [course])),
            ),
          )
          as _i6.Future<_i2.Course>);
}

/// A class which mocks [RecommendationEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationEngine extends _i1.Mock
    implements _i8.RecommendationEngine {
  MockRecommendationEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ContextDetector get contextDetector =>
      (super.noSuchMethod(
            Invocation.getter(#contextDetector),
            returnValue: _FakeContextDetector_1(
              this,
              Invocation.getter(#contextDetector),
            ),
          )
          as _i3.ContextDetector);

  @override
  _i4.CourseScorer get courseScorer =>
      (super.noSuchMethod(
            Invocation.getter(#courseScorer),
            returnValue: _FakeCourseScorer_2(
              this,
              Invocation.getter(#courseScorer),
            ),
          )
          as _i4.CourseScorer);

  @override
  List<_i9.ScoredCourse> recommend({
    required List<_i2.Course>? courses,
    required _i7.UserRunningProfile? profile,
    required double? userLat,
    required double? userLng,
    required _i10.RunningContext? context,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recommend, [], {
              #courses: courses,
              #profile: profile,
              #userLat: userLat,
              #userLng: userLng,
              #context: context,
              #limit: limit,
            }),
            returnValue: <_i9.ScoredCourse>[],
          )
          as List<_i9.ScoredCourse>);

  @override
  _i3.ContextDetectionResult detectContext({
    required DateTime? currentTime,
    required DateTime? lastRunAt,
    required List<String>? recentCourseIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#detectContext, [], {
              #currentTime: currentTime,
              #lastRunAt: lastRunAt,
              #recentCourseIds: recentCourseIds,
            }),
            returnValue: _FakeContextDetectionResult_3(
              this,
              Invocation.method(#detectContext, [], {
                #currentTime: currentTime,
                #lastRunAt: lastRunAt,
                #recentCourseIds: recentCourseIds,
              }),
            ),
          )
          as _i3.ContextDetectionResult);
}
